export const fakeComments = [
  {
    comment: 'This is nice!',
    creation_date: '2021-01-10',
    username: 'John',
  },
  {
    comment: 'Great content!',
    creation_date: '2021-02-10',
    username: 'Jane',
  },
];

export const fakeCards = [
  {
    id: 23771716,
    name: '7 Colored Fish',
    type: 'Normal Monster',
    desc: 'A rare rainbow fish that has never been caught by mortal man.',
    atk: 1800,
    def: 800,
    level: 4,
    race: 'Fish',
    attribute: 'WATER',
    card_sets: [
      {
        set_name: 'Gold Series',
        set_code: 'GLD1-EN001',
        set_rarity: 'Common',
        set_rarity_code: '(C)',
        set_price: '0.74',
      },
      {
        set_name: 'Metal Raiders',
        set_code: 'MRD-098',
        set_rarity: 'Common',
        set_rarity_code: '(C)',
        set_price: '1.06',
      },
      {
        set_name: 'Metal Raiders',
        set_code: 'MRD-E098',
        set_rarity: 'Common',
        set_rarity_code: '(C)',
        set_price: '2.63',
      },
      {
        set_name: 'Metal Raiders',
        set_code: 'MRD-EN098',
        set_rarity: 'Common',
        set_rarity_code: '(C)',
        set_price: '2.95',
      },
      {
        set_name: 'Starter Deck: Joey',
        set_code: 'SDJ-008',
        set_rarity: 'Common',
        set_rarity_code: '(C)',
        set_price: '1.02',
      },
      {
        set_name: 'Structure Deck: Fury from the Deep',
        set_code: 'SD4-EN002',
        set_rarity: 'Common',
        set_rarity_code: '(C)',
        set_price: '1.12',
      },
    ],
    card_images: [
      {
        id: 23771716,
        image_url: 'https://storage.googleapis.com/ygoprodeck.com/pics/23771716.jpg',
        image_url_small: 'https://storage.googleapis.com/ygoprodeck.com/pics_small/23771716.jpg',
      },
    ],
    card_prices: [
      {
        cardmarket_price: '0.07',
        tcgplayer_price: '0.23',
        ebay_price: '1.75',
        amazon_price: '0.25',
        coolstuffinc_price: '0.25',
      },
    ],
  },
  {
    id: 42431843,
    name: 'Ancient Brain',
    type: 'Normal Monster',
    desc: 'A fallen fairy that is powerful in the dark.',
    atk: 1000,
    def: 700,
    level: 3,
    race: 'Fiend',
    attribute: 'DARK',
    card_sets: [
      {
        set_name: 'Metal Raiders',
        set_code: 'MRD-082',
        set_rarity: 'Common',
        set_rarity_code: '(C)',
        set_price: '1.03',
      },
      {
        set_name: 'Metal Raiders',
        set_code: 'MRD-E082',
        set_rarity: 'Common',
        set_rarity_code: '(C)',
        set_price: '13.17',
      },
      {
        set_name: 'Metal Raiders',
        set_code: 'MRD-EN082',
        set_rarity: 'Common',
        set_rarity_code: '(C)',
        set_price: '2.95',
      },
      {
        set_name: 'Speed Duel: Trials of the Kingdom',
        set_code: 'SBTK-EN004',
        set_rarity: 'Common',
        set_rarity_code: '(C)',
        set_price: '0.96',
      },
    ],
    card_images: [
      {
        id: 42431843,
        image_url: 'https://storage.googleapis.com/ygoprodeck.com/pics/42431843.jpg',
        image_url_small: 'https://storage.googleapis.com/ygoprodeck.com/pics_small/42431843.jpg',
      },
    ],
    card_prices: [
      {
        cardmarket_price: '0.09',
        tcgplayer_price: '0.13',
        ebay_price: '6.49',
        amazon_price: '1.28',
        coolstuffinc_price: '0.25',
      },
    ],
  },
  {
    id: 93221206,
    name: 'Ancient Elf',
    type: 'Normal Monster',
    desc: 'This elf is rumored to have lived for thousands of years. He leads an army of spirits against his enemies.',
    atk: 1450,
    def: 1200,
    level: 4,
    race: 'Spellcaster',
    attribute: 'LIGHT',
    card_sets: [
      {
        set_name: 'Metal Raiders',
        set_code: 'MRD-037',
        set_rarity: 'Common',
        set_rarity_code: '(C)',
        set_price: '1.07',
      },
      {
        set_name: 'Metal Raiders',
        set_code: 'MRD-E037',
        set_rarity: 'Common',
        set_rarity_code: '(C)',
        set_price: '9.17',
      },
      {
        set_name: 'Metal Raiders',
        set_code: 'MRD-EN037',
        set_rarity: 'Common',
        set_rarity_code: '(C)',
        set_price: '0.00',
      },
      {
        set_name: 'Starter Deck: Yugi',
        set_code: 'SDY-024',
        set_rarity: 'Common',
        set_rarity_code: '(C)',
        set_price: '1.01',
      },
      {
        set_name: 'Starter Deck: Yugi',
        set_code: 'SDY-E022',
        set_rarity: 'Common',
        set_rarity_code: '(C)',
        set_price: '23.28',
      },
    ],
    card_images: [
      {
        id: 93221206,
        image_url: 'https://storage.googleapis.com/ygoprodeck.com/pics/93221206.jpg',
        image_url_small: 'https://storage.googleapis.com/ygoprodeck.com/pics_small/93221206.jpg',
      },
    ],
    card_prices: [
      {
        cardmarket_price: '0.03',
        tcgplayer_price: '0.20',
        ebay_price: '0.99',
        amazon_price: '0.68',
        coolstuffinc_price: '0.25',
      },
    ],
  },
  {
    id: 43230671,
    name: 'Ancient Lizard Warrior',
    type: 'Normal Monster',
    desc: 'Before the dawn of man, this lizard warrior ruled supreme.',
    atk: 1400,
    def: 1100,
    level: 4,
    race: 'Reptile',
    attribute: 'EARTH',
    card_sets: [
      {
        set_name: 'Metal Raiders',
        set_code: 'MRD-050',
        set_rarity: 'Common',
        set_rarity_code: '(C)',
        set_price: '0.95',
      },
      {
        set_name: 'Metal Raiders',
        set_code: 'MRD-E050',
        set_rarity: 'Common',
        set_rarity_code: '(C)',
        set_price: '9.74',
      },
      {
        set_name: 'Metal Raiders',
        set_code: 'MRD-EN050',
        set_rarity: 'Common',
        set_rarity_code: '(C)',
        set_price: '1.72',
      },
    ],
    card_images: [
      {
        id: 43230671,
        image_url: 'https://storage.googleapis.com/ygoprodeck.com/pics/43230671.jpg',
        image_url_small: 'https://storage.googleapis.com/ygoprodeck.com/pics_small/43230671.jpg',
      },
    ],
    card_prices: [
      {
        cardmarket_price: '0.16',
        tcgplayer_price: '0.17',
        ebay_price: '0.99',
        amazon_price: '0.80',
        coolstuffinc_price: '0.25',
      },
    ],
  },
  {
    id: 15480588,
    name: 'Armored Lizard',
    type: 'Normal Monster',
    desc: 'A lizard with a very tough hide and a vicious bite.',
    atk: 1500,
    def: 1200,
    level: 4,
    race: 'Reptile',
    attribute: 'EARTH',
    card_sets: [
      {
        set_name: 'Dark Beginning 1',
        set_code: 'DB1-EN143',
        set_rarity: 'Common',
        set_rarity_code: '(C)',
        set_price: '1.01',
      },
      {
        set_name: 'Metal Raiders',
        set_code: 'MRD-005',
        set_rarity: 'Common',
        set_rarity_code: '(C)',
        set_price: '0.96',
      },
      {
        set_name: 'Metal Raiders',
        set_code: 'MRD-E005',
        set_rarity: 'Common',
        set_rarity_code: '(C)',
        set_price: '4.89',
      },
      {
        set_name: 'Metal Raiders',
        set_code: 'MRD-EN005',
        set_rarity: 'Common',
        set_rarity_code: '(C)',
        set_price: '2.95',
      },
      {
        set_name: 'Starter Deck: Joey',
        set_code: 'SDJ-009',
        set_rarity: 'Common',
        set_rarity_code: '(C)',
        set_price: '0.98',
      },
    ],
    card_images: [
      {
        id: 15480588,
        image_url: 'https://storage.googleapis.com/ygoprodeck.com/pics/15480588.jpg',
        image_url_small: 'https://storage.googleapis.com/ygoprodeck.com/pics_small/15480588.jpg',
      },
    ],
    card_prices: [
      {
        cardmarket_price: '0.09',
        tcgplayer_price: '0.13',
        ebay_price: '0.99',
        amazon_price: '0.69',
        coolstuffinc_price: '0.25',
      },
    ],
  },
];